version: '3.8'
x-docker: &default-project
  PROJECT_NAME: ${PROJECT_NAME}

services:
  app:
    build: .
    container_name: "${PROJECT_NAME}_app"
    labels:
      - "com.docker.compose.project=${PROJECT_NAME}"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SPOTIFY_API_CLIENT_ID=${SPOTIFY_API_CLIENT_ID}
      - SPOTIFY_API_CLIENT_SECRET=${SPOTIFY_API_CLIENT_SECRET}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: "${PROJECT_NAME}_db"
    labels:
      - "com.docker.compose.project=${PROJECT_NAME}"
    environment:
      - POSTGRES_DB=music_stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
