version: '3.8'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRES_DB=music_stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SPOTIFY_API_CLIENT_ID=${SPOTIFY_API_CLIENT_ID}
      - SPOTIFY_API_CLIENT_SECRET=${SPOTIFY_API_CLIENT_SECRET}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=music_stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:

